name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: check
        uses: actions/checkout@v2
      - name: Setup JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'adopt'

      - name: action&maven
        run: mvn -B package --file pom.xml

      - name: test
        run: mvn test

              - name: Send Telegram notification
        uses: appleboy/telegram-action@master
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }} # Ваш токен бота
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }} # ID чата в Telegram
          message: |
            Тесты успешно завершены! 🎉
            
            ${{ job.status }}: ${{ job.conclusion }}
            
            Подробнее: ${{ github.run_url }}
            
            ${{ github.event.repository.owner }}/${{ github.event.repository.name }}@${{ github.sha }}

      - name: Send Telegram notification on failure
        uses: appleboy/telegram-action@master
        if: ${{ failure() }}
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chat_id: ${{ secrets.TELEGRAM_CHAT_ID }}
          message: |
            Тесты не прошли! 🚨
            
            ${{ job.status }}: ${{ job.conclusion }}
            
            Подробнее: ${{ github.run_url }}
            
            ${{ github.event.repository.owner }}/${{ github.event.repository.name }}@${{ github.sha }}
            
            ${{ steps.build.outputs.failed-tests }}

